import os

AZURE_ORGANIZATION_NAME = os.getenv("AZURE_ORGANIZATION_NAME", "SpikeeLabs")
AZURE_PROJECT_NAME = os.getenv("AZURE_PROJECT_NAME", "BillingLabs")
AZURE_PERSONAL_ACCESS_TOKEN = os.getenv("AZURE_PERSONAL_ACCESS_TOKEN")
